### ISSUE TITLE
Does new attribution clause apply to this version?

### ISSUE THREAD

**Issue by LoveBodhi** [freepats/muldjordkit#1]
https://www.drumgizmo.org/wiki/doku.php?id=kits:muldjordkit

> Attribution requirement as per January 2021: When used in compositions, attribution must be made in the album credits (or similar album liner notes) as “Drum samples provided by DrumGizmo.org”. In cases where album credits (or similar album liner notes) aren't available it can be left out completely.

**Comment by zenvoid** [comment]
Since the original authors have stated that they want to receive credit for their work, I think that their wish should be respected, even if this derivative version was made before 2021. It seems to me the correct thing to do.

Personally, I think that the CC-BY license **always** requires credits when using content covered by it, even when it is not explicitly mentioned in their download pages, because it's required by the license itself. This is my interpretation of the full CC-BY text. Other people may have different interpretations, but that's what I think.

By popular demand, FreePats will avoid the CC-BY license in the future. This library will be kept because there are many people using it (mainly users of the Hydrogen Drum Machine), but we will stick to CC0 content from now on.

**Comment by LoveBodhi** [comment]
The new clause could be added in the "Readme" file.

**Comment by zenvoid** [comment]
Merged your PR, thank you
